apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikas
spec:
  replicas: 1
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: vikas   # container name must match Jenkinsfile
        image: vikas956059/python:latestdbj
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: python
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000

