apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: vikas   # container name must match Jenkinsfile
        image: vikas956059/python:BUILD_NUMBER
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: python
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000

